name: SEO Indexing

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar main.py
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py

      - name: Enviar correo con resumen
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[SEO Indexing] Informe diario"
          to: jcarrasquet@gmail.com
          from: SeoIdyllica <jcarrasquet@gmail.com>
          body: file://resumen.txt

      - name: Commit CSV actualizado
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add enviados_a_google.csv resumen.txt
          if git diff --cached --quiet; then
            echo "No hay cambios que hacer commit."
          else
            git commit -m "🔄 Actualizar historial diario de URLs procesadas"
            git push
          fi


