name: SEO Indexing

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 03:00 UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  run-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar main.py
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py

      - name: Leer resumen para correo
        id: mailout
        run: |
          {
            echo "content<<EOF"
            cat resumen.txt
            echo "EOF"
          } | tee -a $GITHUB_OUTPUT

      - name: Enviar correo con resumen
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[SEO Indexing] Informe diario"
          to: tu-correo@ejemplo.com
          from: SeoIdyllica <tu-correo@ejemplo.com>
          body: ${{ steps.mailout.outputs.content }}

